var ISSUER = exports.ISSUER = {
    RIPPLE_TRADE_JAPAN : 'rMAz5ZnK73nyNUL4foAvaxdreczCkG3vA6',
    RIPPLE_MARKET_JAPAN : 'rJRi8WW24gt9X85PHAxfWNPCizMMhqUQwg',
    TOKYOJPY : 'r94s8px6kSw1uZ1MV98dhSRTvc6VMPoPcN',
}


